// eslint-disable-next-line import/prefer-default-export
export const Actions = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  GET_AUTH_ERRORS: 'GET_AUTH_ERRORS',
  GET_SELECT_DATA: 'GET_SELECT_DATA',
  GET_SUBSELECT_DATA: 'GET_SUBSELECT_DATA',

  GET_PRODUCT_DATA: 'GET_PRODUCT_DATA',
  GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
  UPDATE_PRODUCT_DATA: 'UPDATE_PRODUCT_DATA',
  DELETE_PRODUCT_DATA: 'DELETE_PRODUCT_DATA',
  CREATE_PRODUCT_DATA: 'CREATE_PRODUCT_DATA',

  GET_REPORT_DATA: 'GET_REPORT_DATA',
  GET_REPORT_DETAILS: 'GET_REPORT_DETAILS',
  UPDATE_REPORT_DATA: 'UPDATE_REPORT_DATA',
  DELETE_REPORT_DATA: 'DELETE_REPORT_DATA',
  CREATE_REPORT_DATA: 'CREATE_REPORT_DATA',

  GET_ANALYTICS_DATA: 'GET_ANALYTICS_DATA',
  GET_FILTEROPTION_DATA: 'GET_FILTEROPTION_DATA',
  GET_REPORTFIELD_DATA: 'GET_REPORTFIELD_DATA',

  GET_SUBSCRIPTION_DATA: 'GET_SUBSCRIPTION_DATA',
  GET_SUBSCRIPTION_DETAILS: 'GET_SUBSCRIPTION_DETAILS',
  UPDATE_SUBSCRIPTION_DATA: 'UPDATE_SUBSCRIPTION_DATA',
  DELETE_SUBSCRIPTION_DATA: 'DELETE_SUBSCRIPTION_DATA',
  CREATE_SUBSCRIPTION_DATA: 'CREATE_SUBSCRIPTION_DATA',

  GET_CATEGORY_DATA: 'GET_CATEGORY_DATA',
  GET_PLAN_DATA: 'GET_PLAN_DATA',

  GET_SHOP_DATA: 'GET_SHOP_DATA',
  UPDATE_SHOP_DATA: 'UPDATE_SHOP_DATA',

  GET_NOTIFICATION_DATA: 'GET_NOTIFICATION_DATA',
  UPDATE_NOTIFICATION_DATA: 'UPDATE_NOTIFICATION_DATA',

  CREATE_SCHEDULE_DATA: 'CREATE_SCHEDULE_DATA',
  GET_SCHEDULE_DATA: 'GET_SCHEDULE_DATA',
  GET_SCHEDULE_DETAILS: 'GET_SCHEDULE_DETAILS',
  UPDATE_SCHEDULE_DATA: 'UPDATE_SCHEDULE_DATA',
  DELETE_SCHEDULE_DATA: 'DELETE_SCHEDULE_DATA',
  GET_SCHEDULE_NOW: 'GET_SCHEDULE_NOW',

  GET_SCHEDULE_JOB_DATA: 'GET_SCHEDULE_JOB_DATA',
  GET_SHOP_DETAIL: 'GET_SHOP_DETAIL',

  GET_ALL_CURRENT_ANALYTICS: 'GET_ALL_CURRENT_ANALYTICS',
  GET_ALL_PREVIOUS_ANALYTICS: 'GET_ALL_PREVIOUS_ANALYTICS',
  GET_CURRENT_SALES_OVERVIEW: 'GET_CURRENT_SALES_OVERVIEW',
  GET_PREVIOUS_SALES_OVERVIEW: 'GET_PREVIOUS_SALES_OVERVIEW',
  GET_SALES_BREAKDOWN: 'GET_SALES_BREAKDOWN',
  GET_REVENUE_BY_CHANNEL: 'GET_REVENUE_BY_CHANNEL',
  GET_CUSTOMERS_BY_COUNTRY: 'GET_CUSTOMERS_BY_COUNTRY',
  GET_ALL_TAX: 'GET_ALL_TAX',
  GET_ALL_REFUND: 'GET_ALL_REFUND',
  ANALYTICS_SYNC_NOW: 'ANALYTICS_SYNC_NOW',
  GET_ANALYTICS_LAST_DATE: 'GET_ANALYTICS_LAST_DATE',
  GET_CURRENT_CUSTOMERS_BY_MONTH: 'GET_CURRENT_CUSTOMERS_BY_MONTH',
  GET_PREVIOUS_CUSTOMERS_BY_MONTH: 'GET_PREVIOUS_CUSTOMERS_BY_MONTH',

  EXPORT_REPORT: 'EXPORT_REPORT',
};
